# Generated by Django 2.2.6 on 2020-11-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201116_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
